### ISSUE TITLE
CRACO 7 / CRA 5: Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by Snotax** [bviebahn/react-native-star-rating-widget#28]
Hi, after updating to React 18 / CRACO 7 / CRA 5 / Node 19 we encounter this strange error:
Uncaught ReferenceError: exports is not defined

![image](https://user-images.githubusercontent.com/11430940/207600621-88360947-0034-4b33-bdc6-4ca0ca01f67d.png)

This error only happens after building when serving the app. We use the latest version of everything.
Do you have any idea what could provoke such an error?
![image](https://user-images.githubusercontent.com/11430940/207601039-bc7b6c21-7526-4568-b75d-38dd251ead27.png)

tsconfig:
 "compilerOptions": {
    "jsx": "react-jsx",
    "lib": [
      "DOM",
      "DOM.Iterable",
      "esnext",
      "dom"
    ],
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "moduleResolution": "node",
    "noEmit": true,
    "resolveJsonModule": true,
    "strict": true,
    "skipLibCheck": true,
    "target": "esnext"
  },

babel.config:
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
};

**Comment by Snotax** [comment]
Hi, thanks for the fast reply. Awesome! 
We're using a monorepo for react-native-web, android and iOS. 
Yes the web part is CRACO / CRA / Webpack. 

In your older versions 1.2 ? It worked without error.

**Comment by bviebahn** [comment]
I see. So far I couldn't reproduce your error, but I get a different one when trying to use the component with react-native-web: `export 'StarIconProps' (reexported as 'StarIconProps') was not found in './StarIcon' (possible exports: default)`. Looks like it could be related. Unfortunately I don't have time right now, but I will do some research later today or tomorrow.

**Comment by bviebahn** [comment]
I just published a beta version which fixes the error that I was having. I hope this fixes your error too, but I'm not sure. Could you please test it by installing `1.6.0-beta.1`?

**Comment by Snotax** [comment]
Thanks for your fast changes, your above mentioned error doesn't occur anymore. But as soon as we use your package in any component, our bundled application now throws this error:
![image](https://user-images.githubusercontent.com/11430940/207881842-8409ab75-b643-4f91-b7d1-3c5d7e25f58b.png)

It probably has nothing to do with your code, but maybe you have an idea on why this happens.

Thank you in advance !

**Comment by bviebahn** [comment]
I don't really have an idea what's causing this, so I just basically recreated the package using the latest version of `create-react-native-library`. If there's a problem with the configuration of this package I think this might fix it, otherwise I suspect there might be something wrong with your tsconfig. Could you try if you're still seeing this error in `1.6.0-beta.2`?

**Comment by Snotax** [comment]
Seems to work! I think your package is working now. The other problems we now have seem to be with webpack and ESM modules :D Thank you for your fast responses.

**Comment by bviebahn** [comment]
Alright, great! I merged the changes and created a new release `1.6.0`. Thanks for your help!

**Comment by Snotax** [comment]
@bviebahn  We acutally just found out what the problem was with the Uncaught ReferenceError that crashed our whole build.
reac-native-svg: 3.6.0!! As soon as we use 3.6.0 in combination with your package everything crashes. But with 3.5.0 it works fine. FYI

**Comment by bviebahn** [comment]
Interesting, and this still happens with the changes I made? Also, you probably mean react-native-svg: 13.6.0, right? Can you tell me if you are able to use that version of react-native-svg on its own without a crash?

**Comment by Snotax** [comment]
Yes of 13.6 of course, sry. Seems like it, i can draw other Icons with it. But I will try tomorrow again with the SVG's of your package inside our app without the star widget. I will update you.

**Comment by Snotax** [comment]
It's really strange behaviour. If I use <Svg> like in your package but without using the StarRating, it still crashes.
But other implementations of react-native-svg like in NativeBase (where react-native-svg is a dependency there) work. 
I can't really get the hang of it.

13.5.0 works everywhere and 13.6.0 not.

**Comment by bviebahn** [comment]
Yes strange. The icons are very basic and only use SVG, Path and Rect elements, so this seems to be an issue with react-native-svg. (Or your specific setup, since I also use 13.6.0). Let me know if you find out anything else.
